packaging_format = 2

id = "mindmaps"
name = "Mindmaps"
description.en = "Tool for making mind maps"
description.fr = "Outil de creation de cartes mentales"

version = "0.0.20201010~ynh3"

maintainers = []

[upstream]
license = "AGPL-3.0"
website = "https://www.mindmaps.app/"
demo = "https://www.mindmaps.app/"
code = "https://github.com/drichard/mindmaps"

[integration]
yunohost = ">= 11.2"
architectures = "all"
multi_instance = false
ldap = false
sso = false
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/mindmaps"

    [install.init_main_permission]
    help.en = "If enabled, Mindmaps will be accessible by people who doesn’t have an account. This can be changed later via the webadmin."
    help.fr = "Si cette case est cochée, Mindmaps sera accessible aux personnes n’ayant pas de compte. Vous pourrez changer ceci plus tard via la webadmin."
    type = "group"
    default = "visitors"

[resources]
    [resources.system_user]

    [resources.install_dir]

    [resources.permissions]
    main.url = "/"
